/** Frozen QA-only owner-declared plastics wave; source/QA reads only. */
import crypto from "node:crypto"; import {execFileSync} from "node:child_process"; import fs from "node:fs/promises"; import path from "node:path";
const S="noorix_source_inspection_archive159_20260913",T="baseer_noorix_data_migration_qa_20260912",C="baseer_odoo_dev-db-1",tenant="default-tenant-noorix-2024",co="cmnf5xrd0001uy8lm8vja50gp",shaArchive="024606ADD82DCD78DC1835828A12D7B22C56E34924FF998ABF752134160E79E2",dir=".local-backups/noorix-migration/runs/20260913-doha-owner-plastics-qa-1",out=path.join(dir,"doha-owner-plastics-payload.json"),evidenceOut=path.join(dir,"doha-owner-plastics-owner-decision.json");
const q=(db,sql)=>{const x=execFileSync("docker",["exec",C,"psql","-U","odoo","-d",db,"-At","-F","\t","-c",sql],{encoding:"utf8",maxBuffer:64*1024*1024}).trim();return x?x.split("\n").map(y=>y.split("\t")):[]}; const hash=x=>crypto.createHash("sha256").update(JSON.stringify(x)).digest("hex");
const f=x=>{const m=String(x).match(/^(\d+)(?:\.(\d+))?$/);if(!m)throw Error(`amount ${x}`);return `${m[1]}.${(m[2]||"").padEnd(4,"0").slice(0,4)}`},u=x=>{const[a,b]=f(x).split(".");return BigInt(a)*10000n+BigInt(b)},round=(a,b)=>(a*2n+b)/(b*2n),cent=x=>round(u(x),100n),money=x=>`${x/100n}.${String(x%100n).padStart(2,"0")}`;
function price(g){const a=g/115n;let r=g%115n,s="";for(let i=0;i<14;i++){r*=10n;s+=String(r/115n);r%=115n}return `${a}.${s}`}
const decisionReceipt={owner_decision:"all previously-uncategorized Doha Consumer purchase invoices are classified as بلاستيكات",decision_scope:"157 active purchase invoices with null category only",source_company_id:co,account_code:"400001",product_type:"service",vat_rule:"tax15 only when positive source tax; no-tax otherwise",approved_at:"2026-09-13"},decisionSha=hash(decisionReceipt);
const rows=q(S,`SELECT i.id,i.tenant_id,i.company_id,i.invoice_number,COALESCE(i.supplier_invoice_number,''),i.transaction_date::date::text,i.net_amount::text,i.tax_amount::text,i.total_amount::text,i.supplier_id,encode(convert_to(COALESCE(i.notes,''),'UTF8'),'hex'),a.id,a.vault_id,a.amount::text,le.id,le.amount::text,i.created_at::text,i.updated_at::text,a.created_at::text,le.created_at::text FROM invoices i JOIN invoice_vault_allocations a ON a.invoice_id=i.id JOIN ledger_entries le ON le.reference_type='invoice' AND le.reference_id=i.id WHERE i.company_id='${co}' AND i.status='active' AND i.kind='purchase' AND i.category_id IS NULL ORDER BY i.transaction_date,i.invoice_number,i.id`).map(([id,t,c,n,sn,date,net,tax,total,supplier,notes,alloc,vault,aa,ledger,la,cr,up,ac,lc])=>({id,t,c,n,sn,date,net:f(net),tax:f(tax),total:f(total),supplier,notes:Buffer.from(notes,"hex").toString(),alloc,vault,aa:f(aa),ledger,la:f(la),cr,up,ac,lc}));
if(rows.length!==157)throw Error(`expected 157, got ${rows.length}`); for(const r of rows)if(r.t!==tenant||r.c!==co||u(r.aa)!==u(r.total)||u(r.la)!==u(r.total))throw Error(`evidence ${r.n}`);
const cm=q(T,`SELECT company_id::text,source_archive_sha256 FROM baseer_noorix_company_map WHERE source_system='noorix' AND source_tenant_id='${tenant}' AND source_company_id='${co}'`);if(cm.length!==1||+cm[0][0]!==3||cm[0][1]!==shaArchive)throw Error("company map");
const supids=[...new Set(rows.map(r=>r.supplier))].sort(),sup=new Map(q(T,`SELECT m.source_supplier_id,m.partner_id::text,m.source_archive_sha256,COALESCE(p.company_id::text,''),p.supplier_rank::text FROM baseer_noorix_supplier_map m JOIN res_partner p ON p.id=m.partner_id WHERE m.source_system='noorix' AND m.source_tenant_id='${tenant}' AND m.source_company_id='${co}' AND m.source_supplier_id IN (${supids.map(x=>`'${x}'`).join(",")})`).map(([s,p,a,c,r])=>{if(a!==shaArchive||c||+r<1)throw Error(`supplier ${s}`);return[s,+p]}));
const vault=new Map(q(T,`SELECT m.source_vault_id,m.journal_id::text,m.source_archive_sha256,j.code FROM baseer_noorix_liquidity_vault_map m JOIN account_journal j ON j.id=m.journal_id WHERE m.source_system='noorix' AND m.source_tenant_id='${tenant}' AND m.source_company_id='${co}'`).map(([v,j,a,code])=>{if(a!==shaArchive||["PSBNK","PSCSH"].includes(code))throw Error(`vault ${v}`);return[v,+j]}));
const existing=q(T,`SELECT source_invoice_id FROM baseer_noorix_purchase_invoice_map WHERE source_system='noorix' AND source_tenant_id='${tenant}' AND source_company_id='${co}'`);if(existing.length!==98)throw Error("prior safe Doha map count differs");
const mk=tax=>`owner-declared:doha-plastics:${tax?"vat15":"no-tax"}`,decisions=new Map(),docs=[];for(const r of rows){if(!sup.has(r.supplier)||!vault.has(r.vault))throw Error(`map ${r.n}`);const taxable=u(r.tax)>0n,g=cent(r.total),net=taxable?round(g*100n,115n):g,tax=g-net;if((taxable&&(cent(r.net)!==net||cent(r.tax)!==tax))||(!taxable&&(cent(r.net)!==g||cent(r.tax)!==0n)))throw Error(`VAT ${r.n}`);const key=mk(taxable),snap={...decisionReceipt,decision_sha256:decisionSha,mapping_key:key};const d={source_system:"noorix",source_tenant_id:tenant,source_company_id:co,source_mapping_key:key,source_category_id:null,source_category_name:"",source_row_sha256:hash(snap),source_archive_sha256:shaArchive,canonical_key:`doha-owner-plastics:${tax?"vat15":"no-tax"}`,decision:"create_historical_service",target_product_id:null,target_product_code:`NOORIX-HIST-DOHA-400001-OWNER-${taxable?"VAT":"NOTAX"}`,target_product_name:`تاريخي دوحة المستهلك - بلاستيكات (قرار المالك${taxable?" ضريبة 15%":" بدون ضريبة"})`,target_account_id:491,target_account_code:"400001",target_account_type:"expense_direct_cost",tax_policy:taxable?"owner_declared_inclusive_15":"no_tax"};decisions.set(key,d);docs.push({source_system:"noorix",source_tenant_id:tenant,source_company_id:co,source_invoice_id:r.id,source_ledger_id:r.ledger,source_allocation_id:r.alloc,source_vault_id:r.vault,source_supplier_id:r.supplier,source_category_id:null,source_invoice_number:r.n,source_supplier_invoice_number:r.sn,source_document_kind:"purchase",business_date:r.date,month:r.date.slice(0,7),source_net_raw:r.net,source_tax_raw:r.tax,source_total_raw:r.total,source_row_sha256:hash({...r,owner_decision_sha256:decisionSha,mapping_key:key}),source_archive_sha256:shaArchive,canonical_key:`purchase:${co}:${r.id}`,source_asset_id:null,source_asset_row_sha256:null,decision:"create_paid_vendor_bill",category_mapping_key:key,target_product_id:null,target_product_code:d.target_product_code,target_product_name:d.target_product_name,target_account_id:491,target_account_code:"400001",target_partner_id:sup.get(r.supplier),target_payment_journal_id:vault.get(r.vault),target_tax_id:taxable?100:null,price_unit:taxable?price(g):money(g),target_net:money(net),target_tax:money(tax),target_total:money(g),owner_category_decision_sha256:decisionSha});}
const sum=(a,k)=>a.reduce((s,x)=>s+BigInt(x[k].replace(".","")),0n),months=Object.fromEntries([...new Set(docs.map(x=>x.month))].sort().map(m=>{const a=docs.filter(x=>x.month===m);return[m,{documents:a.length,gross:money(sum(a,"target_total"))}]}));const payload={schema_version:1,target_database:T,source_archive_sha256:shaArchive,approved_policy:"general_paid_vendor_bills_native_accounting_monthly_atomic",run_prefix:"20260913-noorix-doha-owner-plastics-qa",company:{source_system:"noorix",source_tenant_id:tenant,source_company_id:co,target_company_id:3},allowlist:{purchase_journal_id:29,purchase_journal_code:"BILL",purchase_tax_id:100,vat_input_account_code:"104041",forbidden_journal_codes:["PSBNK","PSCSH"]},category_decisions:[...decisions.values()],documents:docs,report:{source_documents:docs.length,target_net:money(sum(docs,"target_net")),target_tax:money(sum(docs,"target_tax")),target_gross:money(sum(docs,"target_total")),months}};
await fs.mkdir(dir,{recursive:true});await fs.writeFile(out,JSON.stringify(payload,null,2)+"\n");await fs.writeFile(evidenceOut,JSON.stringify({...decisionReceipt,decision_sha256:decisionSha,payload_path:out,excluded_salary_overtime:{documents:4,gross:"1100.00"}},null,2)+"\n");console.log(JSON.stringify({out,payload_sha256:crypto.createHash("sha256").update(await fs.readFile(out)).digest("hex"),decision_sha256:decisionSha,report:payload.report},null,2));
