/** Read-only builder for fully evidenced Doha Consumer paid purchases/expenses. */
import crypto from "node:crypto";
import { execFileSync } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";

const sourceDb="noorix_source_inspection_archive159_20260913", targetDb="baseer_noorix_data_migration_qa_20260912", container="baseer_odoo_dev-db-1";
const tenant="default-tenant-noorix-2024", companyId="cmnf5xrd0001uy8lm8vja50gp", targetCompanyId=3;
const archive="024606ADD82DCD78DC1835828A12D7B22C56E34924FF998ABF752134160E79E2";
const dir=".local-backups/noorix-migration/runs/20260913-doha-consumer-purchases-qa-1", out=path.join(dir,"doha-consumer-purchase-payload.json"), exclusionsOut=path.join(dir,"doha-consumer-purchase-exclusions.json");
const approved=new Map([
  ["بلاستيكات",[491,"400001","expense_direct_cost","بلاستيكات"]], ["تعبئة وتغليف",[491,"400001","expense_direct_cost","تعبئة وتغليف"]],
  ["كهرباء",[508,"400018","expense","كهرباء"]], ["التأمينات الاجتماعية (GOSI)",[505,"400015","expense","التأمينات الاجتماعية"]], ["ضرائب ورسوم أخرى",[560,"400072","expense","ضرائب ورسوم أخرى"]],
]);
function q(db,sql){if(db==="baseer_dev")throw Error("production forbidden");const s=execFileSync("docker",["exec",container,"psql","-U","odoo","-d",db,"-At","-F","\t","-c",sql],{encoding:"utf8",maxBuffer:64*1024*1024}).trim();return s?s.split("\n").map(x=>x.split("\t")):[]}
const sha=x=>crypto.createHash("sha256").update(JSON.stringify(x)).digest("hex");
const f4=x=>{const m=String(x).match(/^(\d+)(?:\.(\d+))?$/);if(!m)throw Error(`invalid amount ${x}`);const d=(m[2]||"").padEnd(4,"0");if(d.length>4&&/[1-9]/.test(d.slice(4)))throw Error(`precision ${x}`);return `${m[1]}.${d.slice(0,4)}`};
const u4=x=>{const [a,b]=f4(x).split(".");return BigInt(a)*10000n+BigInt(b)}; const rup=(a,b)=>(a*2n+b)/(b*2n); const cents=x=>rup(u4(x),100n); const money=x=>`${x/100n}.${String(x%100n).padStart(2,"0")}`;
function netPrice(g){const w=g/115n;let r=g%115n,s="";for(let i=0;i<14;i++){r*=10n;s+=String(r/115n);r%=115n}return `${w}.${s}`}
const rows=q(sourceDb,`SELECT i.id,i.tenant_id,i.company_id,i.kind,i.invoice_number,COALESCE(i.supplier_invoice_number,''),i.transaction_date::date::text,i.net_amount::text,i.tax_amount::text,i.total_amount::text,i.supplier_id,COALESCE(i.category_id,''),COALESCE(c.name_ar,''),encode(convert_to(COALESCE(i.notes,''),'UTF8'),'hex'),a.id,a.vault_id,a.amount::text,v.type,v.name_ar,v.is_active::text,v.is_archived::text,le.id,le.amount::text,COALESCE(asset.id,''),i.created_at::text,i.updated_at::text,a.created_at::text,le.created_at::text FROM invoices i LEFT JOIN categories c ON c.id=i.category_id JOIN invoice_vault_allocations a ON a.invoice_id=i.id JOIN vaults v ON v.id=a.vault_id JOIN ledger_entries le ON le.reference_type='invoice' AND le.reference_id=i.id LEFT JOIN company_assets asset ON asset.invoice_id=i.id WHERE i.company_id='${companyId}' AND i.status='active' AND i.kind IN ('purchase','expense','fixed_expense') ORDER BY i.transaction_date,i.invoice_number,i.id`).map(([id,t,c,k,n,sn,date,net,tax,total,supplier,cat,catName,notes,alloc,vault,allocAmt,vt,vn,va,vr,ledger,ledgerAmt,asset,created,updated,ac,lc])=>({id,t,c,k,n,sn,date,net:f4(net),tax:f4(tax),total:f4(total),supplier,cat:cat||null,catName:catName||"__UNCATEGORIZED__",notes:Buffer.from(notes,"hex").toString("utf8"),alloc,vault,allocAmt:f4(allocAmt),vt,vn,va:va==="true",vr:vr==="true",ledger,ledgerAmt:f4(ledgerAmt),asset:asset||null,created,updated,ac,lc}));
if(rows.length!==259)throw Error(`expected 259 rows, got ${rows.length}`);
for(const r of rows){if(r.t!==tenant||r.c!==companyId||!u4(r.allocAmt)||u4(r.allocAmt)!==u4(r.total)||u4(r.ledgerAmt)!==u4(r.total)||!r.va||r.vr)throw Error(`source payment evidence differs ${r.n}`)}
const company=q(targetDb,`SELECT company_id::text,source_archive_sha256 FROM baseer_noorix_company_map WHERE source_system='noorix' AND source_tenant_id='${tenant}' AND source_company_id='${companyId}'`);if(company.length!==1||+company[0][0]!==targetCompanyId||company[0][1]!==archive)throw Error("company map differs");
const ids=[...new Set(rows.map(r=>r.supplier))].sort();const suppliers=new Map(q(targetDb,`SELECT m.source_supplier_id,m.partner_id::text,m.source_archive_sha256,COALESCE(p.company_id::text,''),p.supplier_rank::text FROM baseer_noorix_supplier_map m JOIN res_partner p ON p.id=m.partner_id WHERE m.source_system='noorix' AND m.source_tenant_id='${tenant}' AND m.source_company_id='${companyId}' AND m.source_supplier_id IN (${ids.map(x=>`'${x}'`).join(",")})`).map(([id,p,a,c,rank])=>{if(a!==archive||c||+rank<1)throw Error(`supplier map differs ${id}`);return[id,+p]}));
const vaults=new Map(q(targetDb,`SELECT m.source_vault_id,m.journal_id::text,m.source_archive_sha256,m.source_vault_type,m.source_vault_name,m.decision,j.code,j.type,j.company_id::text FROM baseer_noorix_liquidity_vault_map m JOIN account_journal j ON j.id=m.journal_id WHERE m.source_system='noorix' AND m.source_tenant_id='${tenant}' AND m.source_company_id='${companyId}'`).map(([v,j,a,t,n,d,code,jt,c])=>{if(a!==archive||d!=="reuse_existing_liquidity"||t!==jt||+c!==targetCompanyId||["PSBNK","PSCSH"].includes(code))throw Error(`vault map differs ${v}`);return[v,+j]}));
const excluded=[],docs=[],decisions=new Map();
for(const r of rows){if(r.catName==="رواتب وأجور"){excluded.push({source_invoice_id:r.id,invoice_number:r.n,gross:r.total,reason:"salary_or_overtime_requires_separate_payroll_evidence"});continue} if(!approved.has(r.catName)){excluded.push({source_invoice_id:r.id,invoice_number:r.n,gross:r.total,category:r.catName,reason:r.catName==="__UNCATEGORIZED__"?"missing_invoice_category_no_safe_operational_classification":"outside_approved_operational_scope"});continue} if(r.asset)throw Error(`approved expense carries asset evidence: ${r.n}`);if(!suppliers.has(r.supplier)||!vaults.has(r.vault))throw Error(`missing supplier/vault map ${r.n}`);
 const [acc,code,type,label]=approved.get(r.catName), taxable=u4(r.tax)>0n, key=`category:${r.cat}:${taxable?"vat15":"no-tax"}`, snap={source_category_id:r.cat,source_category_name:r.catName,mapping_key:key,account_code:code,account_type:type,taxable};
 if(taxable){const g=cents(r.total), net=rup(g*100n,115n);if(cents(r.net)!==net||cents(r.tax)!==g-net)throw Error(`VAT arithmetic differs ${r.n}`)} else if(cents(r.net)!==cents(r.total)||cents(r.tax)!==0n)throw Error(`zero-tax arithmetic differs ${r.n}`);
 const d={source_system:"noorix",source_tenant_id:tenant,source_company_id:companyId,source_mapping_key:key,source_category_id:r.cat,source_category_name:r.catName,source_row_sha256:sha(snap),source_archive_sha256:archive,canonical_key:`doha-consumer:${code}:${r.cat}:${taxable?"vat15":"no-tax"}`,decision:"create_historical_service",target_product_id:null,target_product_code:`NOORIX-HIST-DOHA-${code}-${sha(key).slice(0,10).toUpperCase()}`,target_product_name:`تاريخي دوحة المستهلك - ${label}${taxable?" (ضريبة 15%)":" (بدون ضريبة)"}`,target_account_id:acc,target_account_code:code,target_account_type:type,tax_policy:taxable?"owner_declared_inclusive_15":"no_tax"};decisions.set(key,d);
 const g=cents(r.total),net=taxable?rup(g*100n,115n):g,tax=g-net;docs.push({source_system:"noorix",source_tenant_id:tenant,source_company_id:companyId,source_invoice_id:r.id,source_ledger_id:r.ledger,source_allocation_id:r.alloc,source_vault_id:r.vault,source_supplier_id:r.supplier,source_category_id:r.cat,source_invoice_number:r.n,source_supplier_invoice_number:r.sn,source_document_kind:r.k,business_date:r.date,month:r.date.slice(0,7),source_net_raw:r.net,source_tax_raw:r.tax,source_total_raw:r.total,source_row_sha256:sha({...r,category_policy:snap}),source_archive_sha256:archive,canonical_key:`purchase:${companyId}:${r.id}`,source_asset_id:null,source_asset_row_sha256:null,decision:"create_paid_vendor_bill",category_mapping_key:key,target_product_id:null,target_product_code:d.target_product_code,target_product_name:d.target_product_name,target_account_id:acc,target_account_code:code,target_partner_id:suppliers.get(r.supplier),target_payment_journal_id:vaults.get(r.vault),target_tax_id:taxable?100:null,price_unit:taxable?netPrice(g):money(g),target_net:money(net),target_tax:money(tax),target_total:money(g)});}
if(docs.length!==98||excluded.length!==161)throw Error(`scope cardinality differs ${docs.length}/${excluded.length}`);
const sum=(a,k)=>a.reduce((s,x)=>s+BigInt(x[k].replace(".","")),0n),months=Object.fromEntries([...new Set(docs.map(x=>x.month))].sort().map(m=>{const x=docs.filter(r=>r.month===m);return[m,{documents:x.length,gross:money(sum(x,"target_total"))}]}));
const payload={schema_version:1,target_database:targetDb,source_archive_sha256:archive,approved_policy:"general_paid_vendor_bills_native_accounting_monthly_atomic",run_prefix:"20260913-noorix-doha-consumer-purchases-qa",company:{source_system:"noorix",source_tenant_id:tenant,source_company_id:companyId,target_company_id:targetCompanyId},allowlist:{purchase_journal_id:29,purchase_journal_code:"BILL",purchase_tax_id:100,vat_input_account_code:"104041",forbidden_journal_codes:["PSBNK","PSCSH"]},category_decisions:[...decisions.values()].sort((a,b)=>a.source_mapping_key.localeCompare(b.source_mapping_key)),documents:docs,report:{source_documents:docs.length,target_net:money(sum(docs,"target_net")),target_tax:money(sum(docs,"target_tax")),target_gross:money(sum(docs,"target_total")),months}};
const exclusions={source_documents:rows.length,included_documents:docs.length,excluded_documents:excluded.length,excluded_gross:money(sum(excluded.map(x=>({target_total:x.gross.slice(0,-2)})),"target_total")),exclusions:excluded};
await fs.mkdir(dir,{recursive:true});await fs.writeFile(out,JSON.stringify(payload,null,2)+"\n");await fs.writeFile(exclusionsOut,JSON.stringify(exclusions,null,2)+"\n");console.log(JSON.stringify({outputPath:out,payload_sha256:crypto.createHash("sha256").update(await fs.readFile(out)).digest("hex"),report:payload.report,exclusions:{documents:excluded.length,gross:exclusions.excluded_gross}},null,2));
