"""Reviewed additive corrections; posted native entries remain the financial authority."""
from decimal import Decimal

from odoo import _, api, fields, models, Command
from odoo.exceptions import AccessError, UserError, ValidationError
from odoo.tools.misc import clean_context

from .common import INTERNAL, decimal, money, require_manager


def internal(record):
    return record.env.context.get('baseer_payroll_internal') is INTERNAL


KINDS = [('wage', 'Adjust wage'), ('deduction', 'Adjust other deduction'),
         ('payroll_recovery', 'Reverse payroll advance recovery'),
         ('repayment', 'Reverse latest direct repayment'), ('advance', 'Reverse advance disbursement')]
MOVE_FIELDS = {'baseer_correction_payslip_id', 'baseer_correction_source_id',
               'baseer_correction_kind', 'baseer_correction_reason'}


class CorrectionMove(models.Model):
    _inherit = 'account.move'
    baseer_correction_payslip_id = fields.Many2one('hr.payslip', readonly=True, copy=False, ondelete='restrict', index=True)
    baseer_correction_source_id = fields.Many2one('account.move', readonly=True, copy=False, ondelete='restrict', index=True)
    baseer_correction_kind = fields.Selection(KINDS, readonly=True, copy=False)
    baseer_correction_reason = fields.Text(readonly=True, copy=False)
    _baseer_reversal_once = models.UniqueIndex(
        "(baseer_correction_source_id) WHERE baseer_correction_kind IN ('payroll_recovery', 'repayment', 'advance')",
        'This source has already been reversed through the correction workflow.')

    @api.model_create_multi
    def create(self, vals_list):
        defaults = self.default_get(list(MOVE_FIELDS))
        if not internal(self) and any(any(dict(defaults, **vals).get(key) for key in MOVE_FIELDS) for vals in vals_list):
            raise AccessError(_('Correction links are generated only by the reviewed correction action.'))
        return super().create(vals_list)

    def write(self, vals):
        if not internal(self) and MOVE_FIELDS.intersection(vals):
            raise AccessError(_('Correction links and reasons are immutable.'))
        return super().write(vals)


class CorrectionPayslip(models.Model):
    _inherit = 'hr.payslip'

    @api.model_create_multi
    def create(self, vals_list):
        protected = ['baseer_correction_ids', 'baseer_original_net', 'baseer_adjustment']
        defaults = self.default_get(protected)
        if not internal(self) and any(any(dict(defaults, **vals).get(key) for key in protected) for vals in vals_list):
            raise AccessError(_('Payroll corrections are generated by the reviewed action.'))
        return super().create(vals_list)

    def write(self, vals):
        if not internal(self) and {'baseer_correction_ids', 'baseer_original_net', 'baseer_adjustment'}.intersection(vals):
            raise AccessError(_('Payroll corrections are generated by the reviewed action.'))
        return super().write(vals)

    def action_correct(self):
        self.ensure_one()
        require_manager(self)
        return {'type': 'ir.actions.act_window', 'name': _('Reviewed accounting correction'),
                'res_model': 'baseer.payroll.correction', 'view_mode': 'form', 'target': 'new',
                'context': {'default_slip_id': self.id, 'default_kind': 'wage'}}


class CorrectionLoan(models.Model):
    _inherit = 'baseer.hr.loan'

    @api.model_create_multi
    def create(self, vals_list):
        if not internal(self) and any(vals.get('reversal_move_id', self.env.context.get('default_reversal_move_id')) for vals in vals_list):
            raise AccessError(_('Advance reversal links are generated by the correction action.'))
        return super().create(vals_list)

    def write(self, vals):
        if not internal(self) and 'reversal_move_id' in vals:
            raise AccessError(_('Advance reversal links are immutable.'))
        return super().write(vals)

    def action_correct(self):
        self.ensure_one()
        require_manager(self)
        return {'type': 'ir.actions.act_window', 'name': _('Reviewed accounting correction'),
                'res_model': 'baseer.payroll.correction', 'view_mode': 'form', 'target': 'new',
                'context': {'default_loan_id': self.id, 'default_kind': 'repayment' if self.allocation_ids.filtered(
                    lambda row: not row.reversal_move_id) else 'advance'}}

    def action_view_moves(self):
        action = super().action_view_moves()
        action['domain'] = [('id', 'in', (self.move_id | self.reversal_move_id | self.allocation_ids.move_id | self.allocation_ids.reversal_move_id).ids)]
        return action


class PayrollCorrection(models.TransientModel):
    _name = 'baseer.payroll.correction'
    _description = 'Reviewed Payroll Accounting Correction'

    slip_id = fields.Many2one('hr.payslip', readonly=True)
    loan_id = fields.Many2one('baseer.hr.loan', readonly=True)
    company_id = fields.Many2one('res.company', required=True, default=lambda self: self.env.company, readonly=True)
    currency_id = fields.Many2one(related='company_id.currency_id')
    kind = fields.Selection(KINDS, required=True, default='wage')
    amount = fields.Monetary(string='Signed adjustment', help='Positive wage increases net salary. Positive deduction decreases net salary. Reversals use the original amount.')
    date = fields.Date(required=True, default=fields.Date.context_today)
    reason = fields.Text(required=True)
    reviewed = fields.Boolean(string='I reviewed the original entry, payments and correction evidence')
    source_snapshot = fields.Json(readonly=True)
    move_id = fields.Many2one('account.move', readonly=True)

    def _sources(self):
        self.ensure_one()
        if bool(self.slip_id) == bool(self.loan_id):
            raise ValidationError(_('Choose exactly one payroll or advance source.'))
        source = self.slip_id or self.loan_id
        require_manager(source)
        if source.company_id != self.company_id or self.company_id != self.env.company:
            raise AccessError(_('Switch to the company that owns this record.'))
        source._lock()
        if self.slip_id and (not self.slip_id.baseer_managed or self.slip_id.state != 'done' or self.slip_id.move_id.state != 'posted'):
            raise ValidationError(_('Only posted Baseer payroll can be corrected.'))
        if self.loan_id and (self.loan_id.state not in ('running', 'closed') or self.loan_id.move_id.state != 'posted' or self.loan_id.reversal_move_id):
            raise ValidationError(_('Only an issued advance without a disbursement reversal can be corrected.'))
        return source

    def _snapshot(self):
        source = self._sources()
        loans = self.loan_id or self.env['baseer.hr.loan'].search([
            ('employee_id', '=', source.employee_id.id), ('company_id', '=', self.company_id.id)])
        return {'source': source.id, 'move': source.move_id.id,
                'net': str(money(self.slip_id.baseer_net)) if self.slip_id else False,
                'residual': str(money(self.slip_id.baseer_residual if self.slip_id else source.balance)),
                'corrections': self.slip_id.baseer_correction_ids.ids if self.slip_id else [],
                'active_recoveries': sorted(loans.allocation_ids.filtered(lambda row: not row.reversal_move_id).ids),
                'recovery_history': sorted([row.id, row.reversal_move_id.id or 0] for row in loans.allocation_ids)}

    @api.model_create_multi
    def create(self, vals_list):
        require_manager(self)
        if not self.env.user.has_group('account.group_account_user'):
            raise AccessError(_('Accounting access is required to post a correction.'))
        defaults = self.default_get(['move_id', 'source_snapshot'])
        if any(dict(defaults, **vals).get('move_id') or dict(defaults, **vals).get('source_snapshot') for vals in vals_list):
            raise AccessError(_('Correction results and source evidence are generated automatically.'))
        records = super().create(vals_list)
        for record in records:
            record.with_context(baseer_payroll_internal=INTERNAL).write({'source_snapshot': record._snapshot()})
        return records

    def _lock(self):
        require_manager(self)
        for record in self.sorted('id'):
            self.env.cr.execute('SELECT id FROM baseer_payroll_correction WHERE id=%s FOR UPDATE', [record.id])
            if not self.env.cr.fetchone():
                raise UserError(_('This correction screen expired. Reopen it from the source.'))
        self.invalidate_recordset()

    def write(self, vals):
        if not internal(self):
            self._lock()
            if self.filtered('move_id') or set(vals) - {'kind', 'amount', 'date', 'reason', 'reviewed'}:
                raise AccessError(_('Correction sources and completed results cannot be changed.'))
        return super().write(vals)

    def _new_move(self, source, entries, slip=False, loan=False, full_reverse=False):
        journal = source.journal_id
        if self.date < source.date or self.company_id._get_violated_lock_dates(self.date, False, journal):
            raise ValidationError(_('Choose an open correction date on or after the source entry.'))
        vals = {'move_type': 'entry', 'company_id': self.company_id.id, 'journal_id': journal.id,
                'date': self.date, 'ref': _('Correction of %s', source.name),
                'baseer_correction_source_id': source.id, 'baseer_correction_kind': self.kind,
                'baseer_correction_reason': self.reason.strip(), 'baseer_payslip_id': slip.id if slip else False,
                'baseer_correction_payslip_id': slip.id if slip else False, 'baseer_loan_id': loan.id if loan else False,
                'line_ids': [Command.create(line) for line in entries]}
        if full_reverse:
            vals['reversed_entry_id'] = source.id
        move = self.env['account.move'].with_context(dict(clean_context(self.env.context), baseer_payroll_internal=INTERNAL)).create(vals)
        move.action_post()
        if move.date != self.date:
            raise ValidationError(_('The correction posting date changed. Review the accounting period.'))
        return move

    def _salary_adjustment(self):
        slip = self.slip_id
        amount = decimal(self.amount)
        if not amount.is_finite() or amount != money(amount) or not amount:
            raise ValidationError(_('Enter a nonzero adjustment with at most two decimal places.'))
        delta = amount if self.kind == 'wage' else -amount
        if delta < -money(slip.baseer_residual):
            raise ValidationError(_('A reduction cannot exceed unsettled salary. Recover an actual overpayment separately before reviewing its accounting.'))
        payable_lines = slip.move_id.line_ids.filtered(lambda line: line.account_id.account_type == 'liability_payable')
        account = self.company_id.baseer_salary_expense_id if self.kind == 'wage' else self.company_id.baseer_deduction_account_id
        self.company_id._baseer_check_payroll_configuration()
        if len(payable_lines.account_id) != 1 or len(payable_lines.partner_id) != 1:
            raise ValidationError(_('The original payroll payable source is inconsistent.'))
        partner = payable_lines.partner_id
        entries = [{'name': self.reason.strip(), 'account_id': account.id, 'partner_id': partner.id,
                    'debit': float(max(delta, 0)), 'credit': float(max(-delta, 0))},
                   {'name': self.reason.strip(), 'account_id': payable_lines.account_id.id, 'partner_id': partner.id,
                    'debit': float(max(-delta, 0)), 'credit': float(max(delta, 0))}]
        move = self._new_move(slip.move_id, entries, slip=slip)
        if delta < 0:
            lines = slip._baseer_accounting_moves().line_ids.filtered(lambda line: line.account_id == payable_lines.account_id and not line.reconciled)
            lines.with_context(baseer_payroll_internal=INTERNAL).reconcile()
        return move

    def _reverse_recovery(self):
        Allocation = self.env['baseer.hr.loan.allocation']
        if self.slip_id:
            allocations = Allocation.search([('payslip_id', '=', self.slip_id.id), ('reversal_move_id', '=', False)])
            source = self.slip_id.move_id
        else:
            active = self.loan_id.allocation_ids.filtered(lambda row: not row.reversal_move_id).sorted('id')
            source = active[-1:].move_id
            allocations = active.filtered(lambda row: row.move_id == source)
            if allocations.filtered(lambda row: row.kind != 'repayment'):
                raise ValidationError(_('The latest recovery belongs to payroll. Open that payslip to reverse it.'))
        if not allocations:
            raise ValidationError(_('There is no active recovery to reverse.'))
        for loan in allocations.loan_id:
            active = loan.allocation_ids.filtered(lambda row: not row.reversal_move_id)
            if max(active.ids) not in allocations.ids:
                raise ValidationError(_('Reverse newer advance recoveries before this recovery.'))
        if self.date < max(allocations.mapped('date')):
            raise ValidationError(_('The correction cannot precede its recovery.'))
        if self.slip_id:
            payable = source.line_ids.filtered(lambda line: line.account_id.account_type == 'liability_payable')
            entries = []
            for loan in allocations.loan_id:
                amount = money(sum(decimal(row.amount) for row in allocations.filtered(lambda row: row.loan_id == loan)))
                principal = loan._principal_lines()
                entries.append({'name': self.reason.strip(), 'account_id': principal.account_id.id,
                                'partner_id': principal.partner_id.id, 'debit': float(amount)})
            entries.append({'name': self.reason.strip(), 'account_id': payable.account_id.id,
                            'partner_id': payable.partner_id.id, 'credit': float(money(sum(decimal(row.amount) for row in allocations)))})
            move = self._new_move(source, entries, slip=self.slip_id)
        else:
            entries = [{'name': self.reason.strip(), 'account_id': line.account_id.id, 'partner_id': line.partner_id.id,
                        'debit': line.credit, 'credit': line.debit} for line in source.line_ids]
            move = self._new_move(source, entries, loan=self.loan_id, full_reverse=True)
        for loan in allocations.loan_id:
            rows = allocations.filtered(lambda row: row.loan_id == loan)
            principals = loan._principal_lines()
            partials = principals.matched_credit_ids.filtered(lambda partial: partial.credit_move_id.move_id == source)
            if money(sum(decimal(partial.amount) for partial in partials)) != money(sum(decimal(row.amount) for row in rows)):
                raise ValidationError(_('Recovery history differs from its native reconciliation. Review it before correction.'))
            partials.with_context(baseer_payroll_internal=INTERNAL).unlink()
        accounts = allocations.loan_id._principal_lines().account_id if len(allocations.loan_id) == 1 else allocations.loan_id.mapped('move_id.line_ids').filtered(lambda line: line.debit > 0 and line.account_id.reconcile).account_id
        for account in accounts:
            credits = source.line_ids.filtered(lambda line: line.account_id == account and line.credit > 0)
            debits = move.line_ids.filtered(lambda line: line.account_id == account and line.debit > 0)
            (credits | debits).with_context(baseer_payroll_internal=INTERNAL).reconcile()
        allocations.with_context(baseer_payroll_internal=INTERNAL).write({'reversal_move_id': move.id})
        allocations.loan_id.with_context(baseer_payroll_internal=INTERNAL).write({'state': 'running'})
        return move

    def _reverse_advance(self):
        loan = self.loan_id
        if loan.allocation_ids.filtered(lambda row: not row.reversal_move_id) or money(loan.balance) != money(loan.amount):
            raise ValidationError(_('Reverse all advance recoveries before reversing the disbursement.'))
        previous = loan.allocation_ids.reversal_move_id
        if previous and self.date < max(previous.mapped('date')):
            raise ValidationError(_('The disbursement reversal cannot precede recovery corrections.'))
        source = loan.move_id
        entries = [{'name': self.reason.strip(), 'account_id': line.account_id.id, 'partner_id': line.partner_id.id,
                    'debit': line.credit, 'credit': line.debit} for line in source.line_ids]
        move = self._new_move(source, entries, loan=loan, full_reverse=True)
        principal = loan._principal_lines()
        lines = (principal | move.line_ids.filtered(lambda line: line.account_id == principal.account_id)).filtered(lambda line: not line.reconciled)
        if lines:
            lines.with_context(baseer_payroll_internal=INTERNAL).reconcile()
        loan.with_context(baseer_payroll_internal=INTERNAL).write({'state': 'cancel', 'reversal_move_id': move.id})
        return move

    def action_confirm(self):
        self.ensure_one()
        self._lock()
        if self.move_id:
            return self._open_move()
        if not self.env.user.has_group('account.group_account_user'):
            raise AccessError(_('Accounting access is required to post a correction.'))
        if not self.reviewed or not (self.reason or '').strip():
            raise ValidationError(_('Document the reason and confirm the accounting review.'))
        if self.source_snapshot != self._snapshot():
            raise ValidationError(_('The source balance or history changed. Reopen correction and review the current evidence.'))
        if self.slip_id and self.kind not in ('wage', 'deduction', 'payroll_recovery') or self.loan_id and self.kind not in ('repayment', 'advance'):
            raise ValidationError(_('Choose a correction that belongs to this source.'))
        if self.kind in ('wage', 'deduction'):
            move = self._salary_adjustment()
        elif self.kind in ('payroll_recovery', 'repayment'):
            move = self._reverse_recovery()
        else:
            move = self._reverse_advance()
        self.with_context(baseer_payroll_internal=INTERNAL).write({'move_id': move.id})
        (self.slip_id or self.loan_id).message_post(body=_('Reviewed correction posted: %s. Original history is preserved; no external transfer is sent.', move.display_name))
        return self._open_move()

    def _open_move(self):
        return {'type': 'ir.actions.act_window', 'res_model': 'account.move', 'res_id': self.move_id.id,
                'view_mode': 'form'}
