package sa.abroj.baseersms.v2;
import android.content.Context; import androidx.work.Data; import androidx.work.ExistingWorkPolicy; import androidx.work.OneTimeWorkRequest; import androidx.work.WorkManager; import androidx.work.Worker; import androidx.work.WorkerParameters; import java.io.ByteArrayOutputStream; import java.io.InputStream; import java.io.OutputStream; import java.net.HttpURLConnection; import java.net.URL; import java.nio.charset.StandardCharsets; import java.util.UUID; import org.json.JSONObject;
public final class PairingWorker extends Worker {
    private static final String PAYLOAD="pairing_qr"; public PairingWorker(Context c, WorkerParameters p){super(c,p);}
    static void enqueue(Context c,String qr){ WorkManager.getInstance(c).enqueueUniqueWork("baseer-sms-v2-pair", ExistingWorkPolicy.REPLACE, new OneTimeWorkRequest.Builder(PairingWorker.class).setInputData(new Data.Builder().putString(PAYLOAD,qr).build()).build()); }
    @Override public Result doWork(){ try { Context c=getApplicationContext(); JSONObject qr=new JSONObject(getInputData().getString(PAYLOAD)); String url=qr.getString("url").replaceAll("/+$",""); String token=qr.getString("token"); int version=qr.optInt("v"); if((version != 1 && version != 2) || !url.startsWith("https://") || token.length()<20) throw new Exception("invalid_pairing_qr");
        HttpURLConnection h=(HttpURLConnection)new URL(url+"/baseer-bank-sms/v2/pair").openConnection(); h.setConnectTimeout(15000);h.setReadTimeout(20000);h.setRequestMethod("POST");h.setRequestProperty("Content-Type","application/json");h.setDoOutput(true); JSONObject body=new JSONObject();body.put("pairing_token",token);body.put("installation_id",UUID.randomUUID().toString());try(OutputStream o=h.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}if(h.getResponseCode()!=200)throw new Exception("pairing_rejected");JSONObject reply=new JSONObject(new String(readFully(h.getInputStream()),StandardCharsets.UTF_8));SecureSettings.savePairing(c,url,reply.getString("device_code"),reply.getString("device_secret"));StatusStore.error(c,"");SyncWorker.enqueue(c);return Result.success();
    }catch(Exception e){StatusStore.error(getApplicationContext(),"pairing_failed");return Result.failure();}}
    private static byte[] readFully(InputStream in)throws Exception{try(InputStream s=in;ByteArrayOutputStream o=new ByteArrayOutputStream()){byte[] b=new byte[1024];for(int n;(n=s.read(b))!=-1;)o.write(b,0,n);return o.toByteArray();}}
}
