from datetime import timedelta
import hashlib

from odoo import _, api, fields, models
from odoo.exceptions import AccessError, UserError, ValidationError

from .common import constant_time_equal, fingerprint, new_secret


class BaseerPrintAgent(models.Model):
    """A physical Windows computer, deliberately shared across companies."""

    _name = 'baseer.print.agent'
    _description = 'Baseer Print Agent'
    _order = 'name, id'
    _check_company_auto = False
    _PENDING_DEVICE_PREFIX = 'PENDING-'

    name = fields.Char(required=True)
    # Preserved only for PRINT-1 history; all new authorization is explicit.
    company_id = fields.Many2one('res.company', readonly=True, copy=False, index=True)
    allowed_company_ids = fields.Many2many(
        'res.company', 'baseer_print_agent_company_rel', 'agent_id', 'company_id',
        string='Authorized companies', required=True)
    device_uid = fields.Char(required=True, copy=False, index=True,
                             help='Stable identifier generated by the Windows agent.')
    state = fields.Selection([
        ('new', 'New'), ('online', 'Online'), ('offline', 'Offline'), ('revoked', 'Revoked'),
    ], required=True, default='new', index=True)
    active = fields.Boolean(default=True)
    agent_version = fields.Char(readonly=True)
    last_seen_at = fields.Datetime(readonly=True, index=True)
    token_fingerprint = fields.Char(copy=False, readonly=True, groups='base.group_system')
    pairing_fingerprint = fields.Char(copy=False, readonly=True, groups='base.group_system')
    pairing_expires_at = fields.Datetime(readonly=True)
    pairing_attempts = fields.Integer(default=0, readonly=True)
    runtime_instance_id = fields.Char(readonly=True, copy=False, groups='base.group_system')
    runtime_lease_expires_at = fields.Datetime(readonly=True, copy=False, index=True, groups='base.group_system')

    @api.model_create_multi
    def create(self, vals_list):
        protected = {'state', 'token_fingerprint', 'pairing_fingerprint', 'pairing_expires_at',
                     'pairing_attempts', 'agent_version', 'last_seen_at', 'runtime_instance_id',
                     'runtime_lease_expires_at'}
        for vals in vals_list:
            state = vals.get('state')
            if not self.env.context.get('baseer_print_internal') and (
                    protected.intersection(vals) - {'state'} or state not in (None, 'new')):
                raise AccessError(_('Agent credentials and connection state are controlled by the server.'))
            if not vals.get('allowed_company_ids'):
                vals['allowed_company_ids'] = [(6, 0, [self.env.company.id])]
        return super().create(vals_list)

    @api.constrains('device_uid', 'allowed_company_ids')
    def _check_agent(self):
        for record in self:
            if len((record.device_uid or '').strip()) < 12:
                raise ValidationError(_('The device identifier is not valid.'))
            if not record.allowed_company_ids:
                raise ValidationError(_('Authorize at least one company for the agent.'))
            duplicate = self.search([('id', '!=', record.id), ('device_uid', '=', record.device_uid)], limit=1)
            if duplicate:
                raise ValidationError(_('An agent device identifier may only be used once.'))

    def init(self):
        """PRINT-1 → R1 preflight: preserve paired hardware and quarantine only safe duplicates."""
        # Odoo initialises models one by one.  On a first installation the
        # Agent table can be initialised before the Job table, so never parse
        # a query that references the latter until PostgreSQL confirms it
        # exists.  Upgrades retain the stricter unfinished-job protection.
        self.env.cr.execute("SELECT to_regclass('baseer_print_job')")
        has_job_table = bool(self.env.cr.fetchone()[0])
        unsafe_jobs = ''' OR EXISTS (SELECT 1 FROM baseer_print_job job
                   WHERE job.agent_id = duplicate.id AND job.state IN ('pending', 'leased'))''' if has_job_table else ''
        self.env.cr.execute('''
            SELECT duplicate.device_uid FROM baseer_print_agent duplicate
             WHERE EXISTS (SELECT 1 FROM baseer_print_agent canonical
                           WHERE canonical.device_uid = duplicate.device_uid AND canonical.id < duplicate.id)
               AND (duplicate.state != 'new' %s)
             LIMIT 1
        ''' % unsafe_jobs)
        duplicate = self.env.cr.fetchone()
        if duplicate:
            raise UserError(_('Direct-print migration stopped: duplicate agent %s is paired or has unfinished jobs.') % duplicate[0])
        self.env.cr.execute('''
            INSERT INTO baseer_print_agent_company_rel (agent_id, company_id)
            SELECT legacy.id, legacy.company_id
              FROM baseer_print_agent AS legacy
             WHERE legacy.company_id IS NOT NULL
               AND NOT EXISTS (
                   SELECT 1 FROM baseer_print_agent_company_rel AS relation
                    WHERE relation.agent_id = legacy.id
                      AND relation.company_id = legacy.company_id
               )
        ''')
        safe_new_agents = ''' AND NOT EXISTS (SELECT 1 FROM baseer_print_job job
                               WHERE job.agent_id = duplicate.id AND job.state IN ('pending', 'leased'))''' if has_job_table else ''
        self.env.cr.execute('''
            UPDATE baseer_print_agent AS duplicate SET active = FALSE
             WHERE duplicate.state = 'new'
               AND EXISTS (SELECT 1 FROM baseer_print_agent canonical
                           WHERE canonical.device_uid = duplicate.device_uid AND canonical.id < duplicate.id)
               %s
        ''' % safe_new_agents)

    def _require_admin(self):
        if not self.env.user.has_group('base.group_system'):
            raise AccessError(_('Only a system administrator can manage direct-print hardware.'))

    def _allows_company(self, company):
        self.ensure_one()
        return bool(company and company in self.allowed_company_ids)

    def action_generate_pairing_code(self):
        self.ensure_one()
        self._require_admin()
        code = self._generate_pairing_code()
        return {'type': 'ir.actions.client', 'tag': 'display_notification', 'params': {
            'title': _('Pairing code'),
            'message': _('Use this code once in the Windows agent within 10 minutes: %s') % code,
            'type': 'warning', 'sticky': True,
        }}

    def _generate_pairing_code(self):
        """Create a short-lived server-side pairing secret for an admin flow."""
        self.ensure_one()
        self._require_admin()
        if not self.active or self.state == 'revoked':
            raise ValidationError(_('Enable the agent before creating a pairing code.'))
        code = new_secret(24)
        self.with_context(baseer_print_internal=True).write({
            'pairing_fingerprint': fingerprint(self.env, code),
            'pairing_expires_at': fields.Datetime.now() + timedelta(minutes=10),
            'pairing_attempts': 0,
        })
        return code

    def action_revoke_token(self):
        self.ensure_one()
        self._require_admin()
        self.with_context(baseer_print_internal=True).write({
            'state': 'revoked', 'token_fingerprint': False, 'pairing_fingerprint': False,
            'pairing_expires_at': False, 'runtime_instance_id': False,
            'runtime_lease_expires_at': False,
        })

    @api.model
    def _pair_device(self, pairing_code, device_uid, agent_version):
        if (not isinstance(pairing_code, str) or not isinstance(device_uid, str)
                or not isinstance(agent_version, str)):
            return False
        device_uid = device_uid.strip()
        if not 12 <= len(device_uid) <= 128:
            return False
        code_fingerprint = fingerprint(self.env, pairing_code)
        agent = self.sudo().search([
            ('pairing_fingerprint', '=', code_fingerprint), ('active', '=', True), ('state', '!=', 'revoked'),
        ], limit=1)
        now = fields.Datetime.now()
        if (not agent or not agent.pairing_expires_at or agent.pairing_expires_at < now
                or agent.pairing_attempts >= 5
                or not constant_time_equal(agent.pairing_fingerprint, code_fingerprint)):
            if agent:
                agent.with_context(baseer_print_internal=True).write({'pairing_attempts': agent.pairing_attempts + 1})
            return False
        # Serialise device adoption even when two pending pairing codes submit
        # the same Windows-derived identity at the same time.  This is a
        # transaction-scoped PostgreSQL lock, so it adds no stored state.
        identity_lock = int.from_bytes(hashlib.sha256(device_uid.encode()).digest()[:8], 'big', signed=True)
        self.env.cr.execute('SELECT pg_advisory_xact_lock(%s)', [identity_lock])
        self.env.cr.execute('SELECT id FROM baseer_print_agent WHERE id = %s FOR UPDATE', [agent.id])
        agent.invalidate_recordset()
        now = fields.Datetime.now()
        if (not agent.pairing_expires_at or agent.pairing_expires_at < now
                or agent.pairing_attempts >= 5
                or not constant_time_equal(agent.pairing_fingerprint, code_fingerprint)):
            return False
        pending_identity = agent.state == 'new' and agent.device_uid.startswith(self._PENDING_DEVICE_PREFIX)
        if not pending_identity and agent.device_uid != device_uid:
            agent.with_context(baseer_print_internal=True).write({'pairing_attempts': agent.pairing_attempts + 1})
            return False
        duplicate = self.sudo().search([('id', '!=', agent.id), ('device_uid', '=', device_uid)], limit=1)
        if duplicate:
            agent.with_context(baseer_print_internal=True).write({'pairing_attempts': agent.pairing_attempts + 1})
            return False
        token = new_secret()
        values = {
            'token_fingerprint': fingerprint(self.env, token), 'pairing_fingerprint': False,
            'pairing_expires_at': False, 'pairing_attempts': 0, 'agent_version': agent_version[:64],
            'last_seen_at': now, 'state': 'online', 'runtime_instance_id': False,
            'runtime_lease_expires_at': False,
        }
        if pending_identity:
            values['device_uid'] = device_uid
            values['name'] = device_uid
        agent.with_context(baseer_print_internal=True).write(values)
        return agent, token

    @api.model
    def _from_token(self, raw_token):
        if not raw_token or len(raw_token) > 512:
            return self.browse()
        token_fingerprint = fingerprint(self.env, raw_token)
        agent = self.sudo().search([
            ('token_fingerprint', '=', token_fingerprint), ('active', '=', True), ('state', '!=', 'revoked'),
        ], limit=1)
        return agent if agent and constant_time_equal(agent.token_fingerprint, token_fingerprint) else self.browse()

    def _claim_runtime(self, runtime_id=False):
        """Allow one modern runner per agent, even if configuration is copied."""
        self.ensure_one()
        now = fields.Datetime.now()
        if not runtime_id:
            return not (self.runtime_instance_id and self.runtime_lease_expires_at
                        and self.runtime_lease_expires_at >= now)
        if not isinstance(runtime_id, str) or not 16 <= len(runtime_id) <= 128:
            return False
        self.env.cr.execute('''
            UPDATE baseer_print_agent
               SET runtime_instance_id = %s,
                   runtime_lease_expires_at = NOW() + INTERVAL '90 seconds'
             WHERE id = %s
               AND (runtime_instance_id = %s
                    OR runtime_lease_expires_at IS NULL
                    OR runtime_lease_expires_at < NOW())
            RETURNING id
        ''', [runtime_id, self.id, runtime_id])
        return bool(self.env.cr.fetchone())

    def _release_runtime(self, runtime_id=False):
        """Release only the exact active runtime during a local repair.

        This is deliberately narrower than a force release: a copied agent
        configuration cannot displace a healthy runtime without its random
        current runtime ID. Job leases are separate and intentionally untouched.
        """
        self.ensure_one()
        if not isinstance(runtime_id, str) or not 16 <= len(runtime_id) <= 128:
            return False
        self.env.cr.execute('''
            UPDATE baseer_print_agent
               SET runtime_instance_id = NULL,
                   runtime_lease_expires_at = NULL
             WHERE id = %s
               AND runtime_instance_id = %s
            RETURNING id
        ''', [self.id, runtime_id])
        return bool(self.env.cr.fetchone())

    def _heartbeat(self, version=False, runtime_id=False):
        self.ensure_one()
        if not self._claim_runtime(runtime_id):
            return False
        self.sudo().with_context(baseer_print_internal=True).write({
            'last_seen_at': fields.Datetime.now(), 'state': 'online',
            'agent_version': (version or self.agent_version or '')[:64],
        })
        return True

    def write(self, vals):
        protected = {'token_fingerprint', 'pairing_fingerprint', 'pairing_expires_at', 'pairing_attempts',
                     'agent_version', 'last_seen_at', 'state', 'runtime_instance_id',
                     'runtime_lease_expires_at'}
        if protected.intersection(vals) and not self.env.context.get('baseer_print_internal'):
            raise AccessError(_('Agent credentials and connection state are controlled by the server.'))
        if 'device_uid' in vals and self.filtered('token_fingerprint') and not self.env.context.get('baseer_print_internal'):
            raise AccessError(_('Paired agent identity cannot be changed. Revoke and pair a new agent instead.'))
        return super().write(vals)
