"""Complete reviewed Arabic S2 translations while retaining earlier terms."""
from pathlib import Path
import polib

path = Path('/mnt/qa-evidence/pos_s2_ar.po')
po = polib.pofile(str(path))
translations = {
    '<span class="text-muted">Average per customer</span>': '<span class="text-muted">متوسط المبيعات للعميل</span>',
    '<span class="text-muted">Customers</span>': '<span class="text-muted">العملاء</span>',
    '<span class="text-muted">Total including VAT</span>': '<span class="text-muted">الإجمالي شامل الضريبة</span>',
    'A no-sales operation must have zero sales and zero customers.': 'عند تسجيل تشغيل دون مبيعات، يجب أن تكون المبيعات وعدد العملاء صفرًا.',
    'All summaries on the same date must use the same day schedule.': 'يجب أن تتبع جميع ملخصات التاريخ نفسه نظام الدوام نفسه.',
    'Average Daily Customers': 'متوسط العملاء اليومي',
    'Average Daily Sales': 'متوسط المبيعات اليومية',
    'Cancel closure': 'إلغاء الإغلاق',
    'Cancel this closure and allow sales entries for its dates?': 'هل تريد إلغاء هذا الإغلاق والسماح بإدخال المبيعات خلال تواريخه؟',
    'Cancellation Reason': 'سبب الإلغاء',
    'Cancelled': 'ملغى',
    'Cancelled At': 'تاريخ الإلغاء',
    'Cancelled By': 'ألغاه',
    'Choose a valid date range of at most 366 days.': 'اختر فترة صحيحة لا تتجاوز 366 يومًا.',
    'Closed': 'مغلق',
    'Closed Days': 'أيام الإغلاق',
    'Closure': 'الإغلاق',
    'Closure approval and audit fields are controlled by the server.': 'يتولى النظام تسجيل اعتماد الإغلاق وبياناته الرقابية؛ لا يمكن تعديلها يدويًا.',
    'Closure period': 'فترة الإغلاق',
    'Closures': 'الإغلاقات',
    'Complete Customers': 'عملاء أيام التشغيل المكتملة',
    'Complete Sales': 'مبيعات أيام التشغيل المكتملة',
    'Complete operating day': 'يوم تشغيل مكتمل',
    'Completed operating days': 'أيام التشغيل المكتملة',
    'Completed operating days — sales and customers': 'أيام التشغيل المكتملة — المبيعات والعملاء',
    'Confirm closure': 'تأكيد الإغلاق',
    'Confirmed': 'مؤكد',
    'Confirmed At': 'تاريخ التأكيد',
    'Confirmed By': 'أكّده',
    'Confirmed or cancelled closures cannot be changed. Cancel the closure with a reason instead.': 'لا يمكن تعديل إغلاق مؤكد أو ملغى. لإتاحة العمل خلال إغلاق مؤكد، ألغِه مع توضيح السبب.',
    'Daily averages are unavailable until a complete operating day is recorded.': 'تظهر المتوسطات اليومية بعد تسجيل يوم تشغيل مكتمل واحد على الأقل.',
    'Daily averages — complete operating days': 'المتوسطات اليومية — أيام التشغيل المكتملة',
    'Daily result rows can only be generated by the report.': 'ينشئ التقرير وحده صفوف النتائج اليومية.',
    'Daily result rows cannot be deleted manually.': 'لا يمكن حذف صفوف النتائج اليومية يدويًا.',
    'Daily result rows cannot be edited.': 'لا يمكن تعديل صفوف النتائج اليومية.',
    'Daily sales and customers': 'المبيعات والعملاء يوميًا',
    'Daily sales and customers report': 'تقرير المبيعات والعملاء اليومي',
    'Daily sales result': 'نتيجة المبيعات اليومية',
    'Daily timeline': 'المخطط اليومي',
    'Date From': 'من تاريخ',
    'Date To': 'إلى تاريخ',
    'Dates include the first and last day. A closure records no sales or accounting entries.': 'تشمل الفترة يوم البداية ويوم النهاية. لا ينشئ الإغلاق مبيعات أو قيودًا محاسبية.',
    'Day schedule': 'نظام دوام اليوم',
    'Each complete operating date counts once, regardless of its shifts. Closed and incomplete dates are excluded from daily averages. Recorded totals include approved entries from incomplete dates. Sales include VAT.': 'يُحسب يوم التشغيل المكتمل مرة واحدة مهما كان عدد شفتاته. تُستبعد أيام الإغلاق والأيام غير المكتملة من المتوسطات اليومية. وتشمل الإجماليات المسجلة الملخصات المعتمدة للأيام غير المكتملة. المبيعات شاملة للضريبة.',
    'Eid': 'عيد',
    'Enter a cancellation reason first.': 'أدخل سبب الإلغاء أولًا.',
    'Enter a nonnegative amount with at most two decimals, no greater than 999999999.99.': 'أدخل مبلغًا يساوي صفرًا أو أكثر، بمنزلتين عشريتين كحد أقصى، ولا يتجاوز 999999999.99.',
    'Enter a sales amount, or explicitly declare an operating day with no sales.': 'أدخل مبلغ المبيعات، أو فعّل خيار التشغيل دون مبيعات.',
    'Evening only': 'مسائي فقط',
    'Full day': 'دوام كامل',
    'Generated': 'تم إعداد التقرير',
    'Has Sales': 'لديه بيانات مبيعات',
    'Holiday': 'إجازة',
    'Incomplete Days': 'أيام غير مكتملة',
    'Incomplete day': 'يوم غير مكتمل',
    'Line': 'الصف',
    'Maintenance': 'صيانة',
    'Missing Days': 'أيام دون إدخال',
    'Missing entry': 'لم يُدخل الملخص',
    'Morning and evening': 'صباحي ومسائي',
    'Morning only': 'صباحي فقط',
    'No payment methods are configured for this company.': 'لم تُضبط طرق الدفع لهذه الشركة.',
    'Only a POS manager can cancel a closure.': 'يستطيع مدير نقاط البيع فقط إلغاء الإغلاق.',
    'Only confirmed closures can be cancelled.': 'يمكن إلغاء الإغلاقات المؤكدة فقط.',
    'Only draft closures can be confirmed.': 'يمكن تأكيد الإغلاقات المسودة فقط.',
    'Only draft closures can be deleted.': 'يمكن حذف الإغلاقات المسودة فقط.',
    'Only the report creator can use these results.': 'يستطيع مُنشئ التقرير فقط استخدام هذه النتائج.',
    'Operating Days': 'أيام التشغيل المكتملة',
    'Operating closure': 'تسجيل إغلاق',
    'Operating closures': 'الإجازات والإغلاقات',
    'Operating date': 'تاريخ التشغيل',
    'Optional closure details': 'تفاصيل الإغلاق (اختياري)',
    'Other': 'سبب آخر',
    'Period coverage': 'حالة بيانات الفترة',
    'Reason': 'السبب',
    'Recorded Customers': 'إجمالي العملاء المسجل',
    'Recorded Sales': 'إجمالي المبيعات المسجلة',
    'Report': 'التقرير',
    'Report results are calculated by the server.': 'يحسب النظام نتائج التقرير؛ لا يمكن تعديلها يدويًا.',
    'Sales including VAT': 'المبيعات شاملة الضريبة',
    'Sales operating closure': 'إغلاق نشاط المبيعات',
    'Sales summaries': 'ملخصات المبيعات',
    'Show report': 'عرض التقرير',
    'Status': 'الحالة',
    'Summaries': 'الملخصات',
    'The closure company cannot be changed.': 'لا يمكن تغيير شركة الإغلاق.',
    'The closure overlaps an existing sales summary, including drafts.': 'يتعارض الإغلاق مع ملخص مبيعات موجود، بما في ذلك المسودات.',
    'The closure overlaps another confirmed closure.': 'تتداخل الفترة مع إغلاق مؤكد آخر.',
    'The external reference cannot exceed 128 characters.': 'لا يمكن أن يتجاوز المرجع الخارجي 128 حرفًا.',
    'The no-sales declaration must be enabled or disabled.': 'يجب أن تكون قيمة خيار التشغيل دون مبيعات مفعّلة أو غير مفعّلة.',
    'The shift must match the selected day schedule.': 'يجب أن يتوافق الشفت مع نظام دوام اليوم المحدد.',
    'This sales period is closed. Cancel the closure before entering sales.': 'فترة المبيعات هذه مغلقة. ألغِ الإغلاق قبل إدخال المبيعات.',
    'This shift operated without sales and creates no accounting entry. The day counts once in daily averages when all its scheduled shifts are recorded or closed.': 'سُجّل هذا الشفت كتَشغيل دون مبيعات، ولا ينشئ قيدًا محاسبيًا. يُحسب اليوم مرة واحدة في المتوسطات اليومية بعد تسجيل جميع شفتاته المقررة أو إغلاقها.',
    'Worked with no sales': 'تشغيل دون مبيعات',
    'customers': 'عميل',
    'report_id': 'التقرير',
}

before = len(po.untranslated_entries())
for entry in po.untranslated_entries():
    if entry.msgid in translations:
        entry.msgstr = translations[entry.msgid]
        entry.flags = [flag for flag in entry.flags if flag != 'fuzzy']

# Native POS menu override is deliberately retained alongside module terms.
direct = po.find('Direct sales')
if not direct:
    direct = polib.POEntry(msgid='Direct sales', msgstr='مبيعات مباشرة',
                          comment='module: baseer_pos_summary',
                          occurrences=[('model:ir.ui.menu,name:point_of_sale.menu_pos_dashboard', '')])
    po.append(direct)
else:
    direct.msgstr = 'مبيعات مباشرة'
    occurrence = ('model:ir.ui.menu,name:point_of_sale.menu_pos_dashboard', '')
    if occurrence not in direct.occurrences:
        direct.occurrences.append(occurrence)
missing = [entry.msgid for entry in po.untranslated_entries()]
assert not missing, missing
po.save(str(path))
print({'before_missing': before, 'remaining_missing': 0, 'total': len(po),
       'native_direct_sales_override': True})
