"""Apply reviewed Arabic source translations to the exported module catalog."""
from pathlib import Path
import polib

translations = {
    'External sales summaries': 'ملخصات المبيعات الخارجية',
    'External sales summary': 'ملخص المبيعات الخارجية',
    'External POS sales summary': 'ملخص مبيعات نقاط البيع الخارجية',
    'External POS summary payment allocation': 'توزيع طرق دفع ملخص المبيعات',
    'External Summary': 'ملخص خارجي',
    'External Summaries Only': 'مخصص للملخصات الخارجية',
    'Direct sales': 'مبيعات مباشرة', 'Sales and customers': 'المبيعات والعملاء',
    'Sales by payment method': 'المبيعات حسب طريقة الدفع', 'Payment categories': 'فئات طرق الدفع',
    'Summary settings': 'إعدادات الملخصات', 'Summary Category': 'فئة طريقة الدفع',
    'Summary Service Product': 'منتج خدمة الملخص', 'Summary Sales Tax': 'ضريبة المبيعات',
    'POS summary payment category': 'فئة طرق دفع الملخصات',
    'Name': 'المرجع', 'Company': 'الشركة', 'Company Currency': 'عملة الشركة', 'Currency': 'العملة',
    'Business Date': 'تاريخ المبيعات', 'Sales date': 'تاريخ المبيعات',
    'Period Scope': 'الفترة', 'All Day': 'اليوم كاملًا', 'Morning': 'صباحية', 'Evening': 'مسائية', 'Shift': 'الوردية',
    'External Reference': 'مرجع التقرير الخارجي', 'Customer Count': 'عدد العملاء', 'Customers': 'العملاء',
    'Notes': 'ملاحظات', 'Source Attachments': 'مرفقات التقرير', 'Config': 'نقطة بيع الملخصات',
    'State': 'الحالة', 'Draft': 'مسودة', 'Approved': 'معتمد',
    'Amount Gross': 'الإجمالي شامل الضريبة', 'Amount Net': 'المبيعات دون الضريبة', 'Amount Tax': 'الضريبة',
    'Average Per Customer': 'متوسط البيع للعميل', 'Approved By': 'اعتمد بواسطة', 'Approved At': 'تاريخ الاعتماد',
    'Payment Method': 'طريقة الدفع', 'Category': 'الفئة', 'Amount': 'المبلغ شامل الضريبة',
    'Summary': 'الملخص', 'Pos Payment': 'الدفعة الأصلية', 'Cash': 'نقد', 'Bank': 'بنك', 'Applications': 'تطبيقات',
    'Active': 'نشط', 'Sequence': 'الترتيب', 'Kind': 'النوع', 'New': 'جديد',
    'Approve': 'اعتماد', 'Approve and open WhatsApp': 'اعتماد وفتح واتساب', 'Open WhatsApp': 'فتح واتساب',
    'Approve this summary and post its sales and payments?': 'هل تريد اعتماد الملخص وترحيل مبيعاته ودفعاته؟',
    'Approve this summary and prepare its WhatsApp message?': 'هل تريد اعتماد الملخص وتجهيز رسالته في واتساب؟',
    'POS order': 'طلب نقاط البيع', 'Session': 'الجلسة', 'Journal entries': 'القيود المحاسبية',
    "Switch to this summary's company to edit or approve it.": 'فعّل شركة هذا الملخص لتعديله أو اعتماده.',
    'Sales day': 'بيانات يوم المبيعات', 'Reference from the external POS': 'رقم التقرير من نقطة البيع الخارجية',
    'Enter the full sales amount for each payment method, including VAT.': 'أدخل كامل مبلغ المبيعات لكل طريقة دفع، شاملًا ضريبة القيمة المضافة.',
    'Payment amount': 'مبلغ طريقة الدفع', 'Optional notes': 'ملاحظات اختيارية',
    'Total sales': 'إجمالي المبيعات', 'Sales': 'المبيعات', 'Tax': 'الضريبة', 'Net sales': 'المبيعات دون الضريبة', 'Month': 'الشهر',
    'Payment method': 'طريقة الدفع',
    'Enter your external POS sales summary': 'أدخل ملخص مبيعات نقطة البيع الخارجية',
    'One summary for each day or shift, using the active company.': 'ملخص لكل يوم أو وردية، تابع للشركة المفعّلة في الواجهة.',
    'Original POS Order': 'طلب نقاط البيع الأصلي', 'Original POS Session': 'جلسة نقاط البيع الأصلية',
    'Original Accounting Entries': 'القيود المحاسبية الأصلية',
    'Customers: %s': 'عدد العملاء: %s', 'Gross sales: %s': 'إجمالي المبيعات شامل الضريبة: %s',
    'Tax: %s': 'الضريبة: %s', 'Average per customer: %s': 'متوسط البيع للعميل: %s',
    'Approve and save the summary before preparing a WhatsApp message.': 'اعتمد الملخص واحفظه قبل تجهيز رسالة واتساب.',
    'Approved external summaries cannot be changed or deleted.': 'لا يمكن تعديل ملخصات المبيعات المعتمدة أو حذفها.',
    'Customer count must be a whole number between 0 and 10000000.': 'يجب أن يكون عدد العملاء عددًا صحيحًا بين 0 و10000000.',
    'Enter an external report reference of 1 to 128 characters.': 'أدخل مرجع التقرير الخارجي بطول من 1 إلى 128 حرفًا.',
    'Use either one All Day summary or separate Morning and Evening summaries for this company and date.': 'أدخل ملخصًا واحدًا لليوم كاملًا أو ملخصين منفصلين للصباحية والمسائية لهذه الشركة والتاريخ.',
    'Select the dedicated external-summary POS for this company.': 'حدد نقطة البيع المخصصة للملخصات الخارجية لهذه الشركة.',
    'Add at least one payment-method amount before saving the summary.': 'أضف مبلغًا لطريقة دفع واحدة على الأقل قبل حفظ الملخص.',
    'An external summary supports at most 25 payment methods.': 'يمكن إدخال 25 طريقة دفع كحد أقصى في الملخص.',
    'The summary total cannot exceed 999999999.99.': 'لا يمكن أن يتجاوز إجمالي الملخص 999999999.99 ريال.',
    'Summary status, totals and original-document links are controlled by the server.': 'تُحدد حالة الملخص وإجمالياته وروابط مستنداته الأصلية آليًا.',
    'The summary company cannot be changed. Create a new summary in the active company.': 'لا يمكن تغيير شركة الملخص. أنشئ ملخصًا جديدًا في الشركة المفعّلة.',
    'The summary POS configuration cannot be changed.': 'لا يمكن تغيير نقطة البيع المرتبطة بالملخص.',
    'The requested business date is locked. Choose an open date; it will not be shifted automatically.': 'تاريخ المبيعات المحدد في فترة مقفلة. اختر تاريخًا مسموحًا؛ لن يُغيّر التاريخ تلقائيًا.',
    'POS and invoicing permissions are required to approve external summaries.': 'يتطلب اعتماد الملخص صلاحيات نقاط البيع والفوترة.',
    'The dedicated summary POS already has an open session. Resolve it before approving another summary.': 'توجد جلسة مفتوحة لنقطة بيع الملخصات. عالجها قبل اعتماد ملخص آخر.',
    'External report opening; no additional opening cash transaction.': 'افتتاح جلسة التقرير الخارجي دون حركة نقدية افتتاحية إضافية.',
    'The native POS order does not match the summary gross, net and tax amounts.': 'مبالغ طلب نقاط البيع لا تطابق إجمالي الملخص وصافيه وضريبته.',
    'The native POS session did not close and post successfully.': 'لم يكتمل إغلاق جلسة نقاط البيع وترحيلها.',
    'The summary must produce one native service order and one dedicated session without stock movements or duplicate invoices.': 'يجب أن ينتج الملخص طلب خدمة واحدًا وجلسة مخصصة واحدة دون حركات مخزون أو فواتير مكررة.',
    'Every summary accounting entry must be posted in the correct company on the requested business date.': 'يجب ترحيل جميع قيود الملخص في الشركة الصحيحة وبتاريخ المبيعات المحدد.',
    'A native summary accounting entry is not balanced.': 'أحد القيود المحاسبية الناتجة عن الملخص غير متوازن.',
    'Posted native revenue, tax and payments must match the approved summary exactly.': 'يجب أن تطابق الإيرادات والضريبة والدفعات المرحلة مبالغ الملخص المعتمد تمامًا.',
    'Native cash and clearing balances do not match the declared payment methods.': 'أرصدة النقد والتسوية لا تطابق مبالغ طرق الدفع المدخلة.',
    'Allocation company, category and native payment links are controlled by the server.': 'تُحدد شركة توزيع الدفعات وفئته وروابط دفعاته الأصلية آليًا.',
    'Each payment allocation must belong to a saved draft summary.': 'يجب أن يرتبط كل مبلغ بطريقة دفع في ملخص مسودة محفوظ.',
    'Payment allocations cannot be moved between summaries.': 'لا يمكن نقل مبالغ طرق الدفع بين الملخصات.',
    'Enter a positive amount with at most two decimals, no greater than 999999999.99.': 'أدخل مبلغًا موجبًا بمنزلتين عشريتين كحد أقصى، لا يتجاوز 999999999.99.',
    'Switch to the summary company before creating or changing this summary.': 'فعّل شركة الملخص قبل إنشائه أو تعديله.',
    'External POS summaries currently support SAR companies only.': 'تدعم ملخصات المبيعات حاليًا الشركات التي تستخدم الريال السعودي فقط.',
    'POS and accounting manager permissions are required to configure external summaries.': 'يتطلب إعداد الملخصات صلاحيات مدير نقاط البيع ومدير المحاسبة.',
    'A summary already exists for this company, date and period.': 'يوجد ملخص لهذه الشركة والتاريخ والفترة بالفعل.',
    'Each payment method may appear only once per summary.': 'يمكن إدخال كل طريقة دفع مرة واحدة فقط في الملخص.',
}

translations.update({
    'Original external summary orders cannot be deleted.': 'لا يمكن حذف طلبات ملخصات المبيعات الخارجية الأصلية.',
    'Original external summary order lines cannot be deleted.': 'لا يمكن حذف بنود طلب ملخص المبيعات الخارجي الأصلي.',
    'External Sales Summary': 'ملخص المبيعات الخارجية',
    'POS source details are not accessible; the full cash amount is retained without inferring tax.': 'لا تتوفر صلاحية الاطلاع على تفاصيل مصدر نقاط البيع؛ تُحتسب الحركة النقدية كاملة دون افتراض ضريبتها.',
    'POS tax portions are rounded for each actual receipt; their sum can differ by a cent from the full source tax.': 'تُقرّب حصة الضريبة لكل تحصيل فعلي؛ وقد يختلف مجموع الحصص بمقدار هللة عن ضريبة المصدر الكاملة.',
    'The native cash count does not match the external summary cash payments.': 'الجرد النقدي لا يطابق الدفعات النقدية في الملخص الخارجي.',
    '<span class="o_stat_text">Journal entries</span>': '<span class="o_stat_text">القيود المحاسبية</span>',
    '<span class="o_stat_text">POS order</span>': '<span class="o_stat_text">طلب نقاط البيع</span>',
    '<span class="o_stat_text">Session</span>': '<span class="o_stat_text">الجلسة</span>',
    'A POS order may belong to only one external summary.': 'لا يمكن ربط طلب نقاط البيع بأكثر من ملخص خارجي واحد.',
    'A POS session may belong to only one external summary.': 'لا يمكن ربط جلسة نقاط البيع بأكثر من ملخص خارجي واحد.',
    'A category used by approved summaries cannot be reclassified. Create a new category instead.': 'لا يمكن تغيير نوع فئة مستخدمة في ملخصات معتمدة. أنشئ فئة جديدة.',
    'A dedicated external summary session must contain exactly its original summary order.': 'يجب أن تحتوي الجلسة المخصصة للملخص على طلب الملخص الأصلي فقط.',
    'A dedicated summary POS cannot be converted to a cashier POS.': 'لا يمكن تحويل نقطة بيع الملخصات إلى نقطة بيع للكاشير.',
    'A linked external summary session cannot be deleted.': 'لا يمكن حذف جلسة مرتبطة بملخص مبيعات خارجي.',
    'A native POS payment may belong to only one allocation.': 'لا يمكن ربط دفعة نقاط البيع بأكثر من مبلغ توزيع واحد.',
    'A summary may own only one POS order.': 'يمكن ربط الملخص بطلب نقاط بيع واحد فقط.',
    'A summary may own only one POS session.': 'يمكن ربط الملخص بجلسة نقاط بيع واحدة فقط.',
    'Allocation': 'توزيع طرق الدفع',
    'Application payments require a separate current-asset clearing account, not a cash account.': 'تتطلب دفعات التطبيقات حساب تسوية مستقلًا من نوع الأصول المتداولة.',
    'Approved POS summaries count only reconciled cash or bank collections; platform clearing is not cash.': 'تحتسب ملخصات نقاط البيع المعتمدة التحصيل النقدي أو البنكي الذي تمت مطابقته؛ ولا تُعد أرصدة تسوية التطبيقات نقدًا.',
    'Bank summary payments must post to an actual bank liquidity account. Use an application category for deferred platform clearing.': 'يجب ترحيل دفعات البنك إلى حساب سيولة بنكية فعلي. استخدم فئة التطبيقات للمبالغ التي تنتظر تسوية المنصة.',
    'Baseer Summary': 'ملخص بصير', 'Baseer cash movement by category': 'الحركة النقدية حسب الفئة — بصير',
    'Cash categories require cash journals; bank and application categories require bank journals.': 'تتطلب فئة النقد دفتر يومية نقديًا، وتتطلب فئتا البنك والتطبيقات دفاتر يومية بنكية.',
    'Choose an active manual summary payment method from this company, without split transactions or foreign currency.': 'اختر طريقة دفع يدوية نشطة للملخص من هذه الشركة، دون تقسيم معاملات أو عملة أجنبية.',
    'Configure a dedicated SAR summary POS with journals, without cash rounding, fiscal positions or presets.': 'أعدّ نقطة بيع مخصصة للملخصات بالريال السعودي مع دفاتر يوميتها، دون تقريب نقدي أو أوضاع ضريبية أو إعدادات مسبقة.',
    'Configure a valid income account on the summary service product or its category.': 'حدد حساب إيراد صالحًا لمنتج خدمة الملخص أو فئته.',
    'Configure an active reconcilable POS intermediary receivable account for this company.': 'حدد حسابًا وسيطًا نشطًا ومستحقًا لنقاط البيع في هذه الشركة، قابلًا للمطابقة.',
    'Configure an active reconcilable outstanding account for this payment method.': 'حدد حساب مبالغ معلقة نشطًا وقابلًا للمطابقة لطريقة الدفع.',
    'Configure an active summary service product for this company.': 'حدد منتج خدمة نشطًا للملخصات في هذه الشركة.',
    'Configure between 1 and 25 summary payment methods, including at most one cash method.': 'أعدّ من 1 إلى 25 طريقة دفع للملخصات، منها طريقة نقدية واحدة كحد أقصى.',
    'Configure full sales tax repartition and its tax accounts before approving summaries.': 'أكمل توزيع ضريبة المبيعات وحساباتها قبل اعتماد الملخصات.',
    'Configure one active simple sales percentage tax on invoice for this company.': 'حدد ضريبة مبيعات نشطة واحدة بنسبة بسيطة، مستحقة عند الفوترة، لهذه الشركة.',
    'Create a new dedicated POS; an existing cashier session history cannot be converted to summaries.': 'أنشئ نقطة بيع مخصصة جديدة؛ لا يمكن تحويل سجل جلسات الكاشير إلى ملخصات.',
    'Created by': 'أنشئ بواسطة', 'Created on': 'تاريخ الإنشاء', 'Last Updated by': 'آخر تحديث بواسطة', 'Last Updated on': 'تاريخ آخر تحديث',
    'Cross-company reconciliation is not permitted.': 'لا يُسمح بالمطابقة بين شركات مختلفة.',
    'Dedicated summary sessions can only be created by approving an external summary.': 'تُنشأ جلسات الملخصات المخصصة من خلال اعتماد ملخص خارجي فقط.',
    'Each application must use its own distinct clearing account.': 'يجب أن يستخدم كل تطبيق حساب تسوية مستقلًا خاصًا به.',
    'External summary POS payments are controlled by summary approval.': 'تُنشأ دفعات نقاط البيع للملخص الخارجي من خلال اعتماد الملخص.',
    'External summary POS payments cannot be deleted.': 'لا يمكن حذف دفعات نقاط البيع المرتبطة بملخص خارجي.',
    'External summary POS payments cannot be edited directly.': 'لا يمكن تعديل دفعات نقاط البيع للملخص الخارجي مباشرةً.',
    'External summary closing does not allow manual balancing differences.': 'لا يسمح إغلاق الملخص الخارجي بإدخال فروق موازنة يدوية.',
    'External summary order lines are controlled by summary approval.': 'تُنشأ بنود طلب الملخص الخارجي من خلال اعتماد الملخص.',
    'External summary order lines cannot be edited directly.': 'لا يمكن تعديل بنود طلب الملخص الخارجي مباشرةً.',
    'External summary orders can only be created by the authorized summary approval.': 'تُنشأ طلبات الملخص الخارجي عبر إجراء الاعتماد المصرح به فقط.',
    'External summary session accounting and links are controlled by summary approval.': 'يُحدد إجراء اعتماد الملخص محاسبة جلسته وروابطها.',
    'Is Current Company': 'تابع للشركة المفعّلة', 'Journal Entry': 'القيد المحاسبي',
    'Only one dedicated summary POS may be configured per company.': 'يمكن إعداد نقطة بيع مخصصة واحدة للملخصات لكل شركة.',
    'Only tax evidenced by posted invoices or approved POS summaries is excluded; unknown tax retains the full cash amount.': 'تُستبعد الضريبة المثبتة بفواتير مرحلة أو ملخصات نقاط بيع معتمدة فقط؛ وتبقى الحركة النقدية كاملة عند غياب الإثبات.',
    'Open the dedicated session through external summary approval.': 'افتح الجلسة المخصصة من خلال اعتماد ملخص المبيعات الخارجي.',
    'Order': 'الطلب', 'Original external summary order amounts and links cannot be edited directly.': 'لا يمكن تعديل مبالغ طلب الملخص الخارجي الأصلي أو روابطه مباشرةً.',
    'POS settlement has no matching receivable balance.': 'لا يوجد رصيد مستحق مطابق لتسوية نقاط البيع.',
    'POS summary accounting evidence is incomplete; its full cash amount is retained.': 'الإثبات المحاسبي لملخص نقاط البيع غير مكتمل؛ تُحتسب الحركة النقدية كاملة.',
    'POS summary cash has no supported positive receivable evidence; its full amount is retained.': 'لا يوجد إثبات مستحق موجب مدعوم للتحصيل النقدي في الملخص؛ يُحتسب المبلغ كاملًا.',
    'POS summary evidence is outside the report company.': 'إثبات ملخص نقاط البيع تابع لشركة أخرى غير شركة التقرير.',
    'Payment methods used by approved summaries cannot be reclassified or assigned different accounts. Create a new method instead.': 'لا يمكن تغيير فئة طريقة دفع مستخدمة في ملخصات معتمدة أو حساباتها. أنشئ طريقة جديدة.',
    'Summary journals must be active and belong to this company and currency.': 'يجب أن تكون دفاتر يومية الملخص نشطة وتابعة للشركة والعملة المحددتين.',
    'The cash journal must have a liquidity account.': 'يجب تحديد حساب سيولة لدفتر اليومية النقدي.',
    'The company of a dedicated summary POS cannot be changed.': 'لا يمكن تغيير شركة نقطة البيع المخصصة للملخصات.',
    'The configured native tax cannot reproduce this gross amount exactly.': 'لا يمكن للضريبة المحددة احتساب هذا المبلغ الإجمالي بصورة مطابقة.',
    'The native session entry must still be draft before applying its business date.': 'يجب أن يكون قيد الجلسة مسودة قبل تطبيق تاريخ المبيعات عليه.',
    'The native session must use the summary dedicated POS configuration.': 'يجب أن تستخدم الجلسة نقطة البيع المخصصة للملخص.',
    'The native summary session entry is unbalanced; approval was rolled back.': 'قيد جلسة الملخص غير متوازن؛ تم التراجع عن الاعتماد.',
    'The payment category company cannot be changed.': 'لا يمكن تغيير شركة فئة طريقة الدفع.',
    'The payment category must belong to the payment method company.': 'يجب أن تتبع الفئة شركة طريقة الدفع نفسها.',
    'Unbalanced counterpart allocation.': 'توزيع غير متوازن للطرف المقابل.',
    'Unproven POS settlement chain.': 'تسلسل تسوية نقاط البيع غير مثبت.',
    'Unreconciled cash counterpart.': 'طرف مقابل للتحصيل النقدي لم تتم مطابقته.',
    'Use External Sales Summaries to post this dedicated POS. Open an ordinary POS for direct sales.': 'استخدم ملخصات المبيعات الخارجية للترحيل في هذه النقطة المخصصة. افتح نقطة بيع عادية للمبيعات المباشرة.',
})

catalog = Path('/mnt/qa-evidence/pos_summary_ar.po')
po = polib.pofile(str(catalog))
if not po.find('Direct sales'):
    po.append(polib.POEntry(msgid='Direct sales', msgstr='مبيعات مباشرة', comment='module: baseer_pos_summary', occurrences=[('model:ir.ui.menu,name:point_of_sale.menu_pos_dashboard','')]))
for entry in po:
    if entry.msgid in translations:
        entry.msgstr = translations[entry.msgid]
po.metadata.update({'Language': 'ar', 'Plural-Forms': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;'})
po.save(str(catalog))
missing = [e.msgid for e in po if not e.msgstr]
Path('/mnt/qa-evidence/pos_summary_translation_missing.json').write_text(__import__('json').dumps(missing,ensure_ascii=False,indent=2))
print('TRANSLATIONS', len(po), 'MISSING',len(missing))

