{
    'name': 'أبرج | تكاليف المشاريع',
    'summary': 'Independent multi-company project costing for Abroj',
    'version': '19.0.1.5.4',
    'category': 'Services/Project Costing',
    'author': 'Abroj',
    'license': 'LGPL-3',
    'depends': ['base', 'product', 'account', 'baseer_document_theme'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/category_data.xml',
        'data/receipt_sequence.xml',
        'reports/project_costing_reports.xml',
        'views/costing_views.xml',
        'views/defaults_views.xml',
        'views/company_views.xml',
        'views/plan_import_views.xml',
        'views/dashboard_views.xml',
        'views/menu.xml',
        'views/material_import_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'abroj_project_costing/static/src/js/dashboard.js',
            'abroj_project_costing/static/src/xml/dashboard.xml',
            'abroj_project_costing/static/src/css/dashboard.css',
            'abroj_project_costing/static/src/css/project_form.css',
            'abroj_project_costing/static/src/css/material_list.css',
            'abroj_project_costing/static/src/js/company_visibility.js',
            'abroj_project_costing/static/src/js/receipt_share.js',
            'abroj_project_costing/static/src/xml/receipt_share.xml',
        ],
    },
    'application': True,
    'installable': True,
}
